stages:
  - build
  - test
  - docker_build
  - security_scan

variables:
  APP_NAME: "cpp-demo-app"
  IMAGE_TAG: "$CI_PIPELINE_ID"

build_cpp:
  stage: build
  image: gcc:13
  script:
    - apt-get update && apt-get install -y cmake
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    paths:
      - build/cpp-demo-app
    expire_in: 1 week

test_cpp:
  stage: test
  image: gcc:13
  dependencies:
    - build_cpp
  script:
    - ./build/cpp-demo-app

docker_build:
  stage: docker_build
  image: docker:24
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $APP_NAME:$IMAGE_TAG .
    - docker save $APP_NAME:$IMAGE_TAG -o image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 day

trivy_scan:
  stage: security_scan
  image:
    name: aquasec/trivy:latest
    entrypoint: [""]
  dependencies:
    - docker_build
  script:
    - trivy image --input image.tar --severity HIGH,CRITICAL --exit-code 1
